name: Zap Server Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      global: |
        PIPENV_VENV_IN_PROJECT=1
        PIPENV_IGNORE_VIRTUALENVS=1

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install pipenv
          pipenv sync --dev
          cp contrib/env-sample .env

      - name: Docker-compose up Zap Server
        run: |
          docker-compose up -d

      - name: Lint with Flake8
        run: |
          pipenv run flake8 .

      - name: Tests with Pytest
        run: |
          export PYTHONPATH=src
          pipenv run pytest apps/tests/test_server_app.py --cov=pypro

      - run: echo "This job's status is ${{ job.status }}."
