name: Zap Server Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      global: |
        PIPENV_VENV_IN_PROJECT=1
        PIPENV_IGNORE_VIRTUALENVS=1

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv sync --dev

      - name: Lint with Flake8
        run: |
          pipenv run flake8 .

      - name: Tests with Pytest
        run: |
          export PYTHONPATH=src
          pipenv run pytest --cov=pypro

      - run: echo "This job's status is ${{ job.status }}."
